---
title: "Wakefield"
output: github_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(here)

source("../R/load_packages.R")

```


## Using data synthesized via the wakefield package by Tyler Rinker to demonstrate propensity score matching

https://www.r-bloggers.com/2016/06/how-to-use-r-for-matching-samples-propensity-score/


## Synthesize

```{r synthesize, warning=FALSE, message=FALSE}

set.seed(1234)
df.patients <- r_data_frame(n = 250, 
                            age(x = 30:78, 
                                name = 'Age'), 
                            sex(x = c("Male", "Female"), 
                                prob = c(0.70, 0.30), 
                                name = "Sex"))
df.patients$Sample <- as.factor('Patients')

summary(df.patients)



set.seed(1234)
df.population <- r_data_frame(n = 1000, 
                              age(x = 18:80, 
                                  name = 'Age'), 
                              sex(x = c("Male", "Female"), 
                                  prob = c(0.50, 0.50), 
                                  name = "Sex"))
df.population$Sample <- as.factor('Population')

summary(df.population)


```


## Merge synthetic dataframes

```{r merge}

mydata <- rbind(df.patients, df.population)
mydata$Group <- as.logical(mydata$Sample == 'Patients')
mydata$Distress <- ifelse(mydata$Sex == 'Male', age(nrow(mydata), x = 0:42, name = 'Distress'),
                                                age(nrow(mydata), x = 15:42, name = 'Distress'))

```


## Compare distributions

```{r dist}

table1 <- CreateTableOne(vars = c('Age', 'Sex', 'Distress'), 
                         data = mydata, 
                         factorVars = 'Sex', 
                         strata = 'Sample')
table1 <- print(table1, 
                printToggle = FALSE, 
                noSpaces = TRUE)
kable(table1[,1:3],  
      align = 'c', 
      caption = 'Table 1: Comparison of unmatched samples')

```

## Matching

```{r matchit}


set.seed(1234)
match.it <- matchit(Group ~ Age + Sex, 
                    data = mydata, 
                    method="nearest",
                    discard = "both", 
                    replace = FALSE,
                    ratio=1)

a <- summary(match.it)

kable(a$nn, digits = 2, align = 'c', 
      caption = 'Table 2: Sample sizes')

kable(a$sum.matched[c(1,2,4)], digits = 2, align = 'c', 
      caption = 'Table 3: Summary of balance for matched data')

plot(match.it, type = 'jitter', interactive = FALSE)


```


## Post match analysis

```{r postmatch}

df.match <- match.data(match.it)[1:ncol(mydata)]
rm(df.patients, df.population)

table4 <- CreateTableOne(vars = c('Age', 'Sex', 'Distress'), 
                         data = df.match, 
                         factorVars = 'Sex', 
                         strata = 'Sample')
table4 <- print(table4, 
                printToggle = FALSE, 
                noSpaces = TRUE)
kable(table4[,1:3],  
      align = 'c', 
      caption = 'Table 4: Comparison of matched samples')

```


## Post match modeling

```{r post_match_model}

hist(df.match$Distress)


lm(Distress ~ Group, data = df.match)

lm(Distress ~ Group + Age + Sex, data = df.match)



```